# Generated by Django 3.2.21 on 2023-09-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmn1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='kyc')),
                ('marital_status', models.CharField(choices=[('national id', 'National ID'), ('passport', 'PassPort')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50)),
                ('next_of_keen', models.CharField(max_length=100)),
                ('identity_type', models.CharField(choices=[('national id', 'National ID'), ('passport', 'PassPort')], max_length=120)),
                ('date_of_birth', models.DateField()),
                ('signature', models.ImageField(upload_to='kyc')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
