# Generated by Django 3.2.21 on 2023-09-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_kyc_identity_image_alter_kyc_identity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
