# Generated by Django 3.2.21 on 2023-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230911_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active'), ('pending', 'Pending')], default='in-active', max_length=100),
        ),
    ]
