# Generated by Django 3.2.21 on 2023-09-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_account_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ref_code',
            new_name='red_code',
        ),
    ]
