# Generated by Django 3.2.21 on 2023-09-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('mastercard', 'Mastercard'), ('visa', 'Visa'), ('verve', 'Verve'), ('wiser', 'Wiser'), ('payoneer', 'Payoneer'), ('iban', 'IBAN'), ('mobile_money_number', 'Mobile Money Number')], default='visa', max_length=20),
        ),
    ]
